/*				 -*- buffer-read-only: t -*- vi: set ro:
** 
** DO NOT EDIT THIS FILE   (debugchn.h)
** 
** It has been AutoGen-ed  Saturday March 30, 2002 at 04:48:40 PM CET
** From the definitions    debugchn.def
** and the template file   debugchn
*/

/*
** Heroes is free software.
** 
** You may redistribute it and/or modify it under the terms of the
** GNU General Public License, as published by the Free Software
** Foundation; either version 2, or (at your option) any later version.
** 
** Heroes is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
** See the GNU General Public License for more details.
** 
** You should have received a copy of the GNU General Public License
** along with Heroes.  See the file "COPYING".  If not,
** write to:  The Free Software Foundation, Inc.,
**            59 Temple Place - Suite 330,
**            Boston,  MA  02111-1307, USA.
*/

typedef enum debug_lvl { 
  D_SECTION          =      1  /* different parts of the game */,
  D_SYSTEM           =      2  /* system related messages */,
  D_RESOURCE         =      4  /* filename resources handling */,
  D_FILE             =      8  /* files and directories handling */,
  D_LEVEL            =     16  /* levels handling */,
  D_SOUND_TRACK      =     32  /* sound track events */,
  D_SOUND_EFFECT     =     64  /* sound effects events */,
  D_VIDEO            =    128  /* communication with the display driver */,
  D_JOYSTICK         =    256  /* joystick initialization and events */,
  D_TIMER            =    512  /* timer handling */,
  D_MISC             =   1024  /* miscellaneous events */,
  D_FADER            =   2048  /* palette fade events */,
  D_BONUS            =   4096  /* bonus */
} debug_lvl;

